### ISSUE TITLE
 Validation Recommended for Lightning Address Input to Prevent Payment Errors

### ISSUE THREAD

**Issue by aChrisYouKnow** [getAlby/go#134]
The current implementation of the "Set Lightning Address" screen appears to lack validation for user input, allowing any string to be converted into a QR code. This can mislead users into thinking they are creating or choosing a new lightning address, even when they enter an incorrect or incomplete address, such as one without an "@" symbol. Worse, if a user enters an existing lightning address that belongs to someone else (thinking they just chose their ____@getalby.com address), any payments made to that address will go to the real owner, not the user. To prevent these issues, a warning should be added to clarify that users need to enter an existing lightning address (i.e. they are not creating one on this screen), and input validation should be implemented to check for an @ symbol in the address.

For those connecting via the Uncle Jim model (the Friends & Family app of Alby Hub) it would be incredible if a randomly generated lightning address could be obtained by the user (something like City4Sky14School@getalby.com) that would just work for them even if they didn't have an Alby account (i.e. payments would go to their isolated sub account of their Uncle Jim's Alby Hub). Or, perhaps a link on that page which directs them to set up an Alby account and get their own lightning address.

**Comment by rolznz** [comment]
Great feedback. Regarding Alby Hub: Alby Hub should soon hopefully be able to generate random lightning addresses for Friends & Family members without them having to create an Alby Account.

**Comment by aChrisYouKnow** [comment]
That would be great!
