### ISSUE TITLE
Need an easier way to delete wallets

### ISSUE THREAD

**Issue by dmnyc** [getAlby/go#148]
It's difficult to remove a wallet from the list without going 2 levels into the settings, and in one instance I have a wallet that was not connected properly but can't be deleted from the list.

Consider adding a swipe-left function to delete (with a confirmation).
![image](https://github.com/user-attachments/assets/e2d73f39-a7d7-4983-a795-fe42cb2bebdd)

**Comment by reneaaron** [comment]
Thanks for reporting, that should be fixed with one of the next releases! :raised_hands: 

Fixed with #143
