### ISSUE TITLE
Error: "Missing Required Capabilities" when adding a new wallet by scanning a QR code from AlbyHub. 

### ISSUE THREAD

**Issue by pcwd** [getAlby/go#151]
Have upgraded from 1.50 to 1.6.0 then 1.6.1.

When adding a new wallet, doesn't matter if scanning a QR code from Albyhub v1.10.1 or copying the connect string, I get the error Missing Required Capabilities.  If I downgrade to 1.50, it will scan the QR code, it will and add the wallet without errors.  If I upgrade to 1.6.1 the wallets I've added already will work find, but I can't add any new wallets without getting that Missing Required Capabilities error.

**Comment by rolznz** [comment]
Hi @pcwd 

Do you set manual permissions in Alby Hub?

**Comment by reneaaron** [comment]
Which backend are you using? Do you use the built-in LDK node, or is it e.g. connected to your LND node?

**Comment by pcwd** [comment]
I use Umbrel with LND.  The Umbrel version of LND is still at 0.18.0.

**Comment by reneaaron** [comment]
Are you using an isolated budget? 

We just discovered a problem related to this report and are about to do a patch release later today. :crossed_fingers:

**Comment by pcwd** [comment]
> Are you using an isolated budget?
> 
Yes.
