### ISSUE TITLE
[Improvement] Simplify Wallet Renaming Flow  

### ISSUE THREAD

**Issue by jpl-btc** [getAlby/go#165]
**Description:**  
Currently, renaming a wallet profile in Alby Go requires several steps, making it less intuitive. Here's the current flow for renaming a wallet named "DEFAULT":  

1. Click the **settings icon** in the top right corner.  
2. Select **Wallets**.  
3. From the list, choose the wallet named “DEFAULT.”  
4. Click the **settings icon** in the top right corner again.  
5. Select **Wallets** once more.  
6. With “DEFAULT” selected, click the **settings icon** next to it to access four options, including the option to rename the wallet.  

**Issue:**  
This flow feels unnecessarily long and could be streamlined for better user experience. It would be helpful to have a simpler way to access the wallet settings, especially since users occasionally skip naming their wallets, leaving them stuck with the placeholder "DEFAULT" (which can be a bit ugly, by default 😄). _There is an [issue ](https://github.com/getAlby/go/issues/127)about this, but these two are separate problems._  

**Suggested Improvement:**  
Provide a quicker, more direct way for users to rename their wallets from the settings page. This would enhance usability and reduce potential frustration, especially for new users.

**Comment by im-adithya** [comment]
@stackingsaunter maybe combine this with #214 so we can go directly to the active wallet settings from the icon
