### ISSUE TITLE
[Feature request] LNURL-withdraw

### ISSUE THREAD

**Issue by Darth-Coin** [getAlby/go#167]
I notice that Alby Go it doesn't support LNURL withdraw feature.
It can be added in the "Receive" button, with a little scan QR icon, for better understanding by the users.
I tried also to use the "Send" QR scanner but it doesn't recognize the LNURL-w.
It's a nice feature and useful in many cases. It should be added to Alby Go.

**Comment by rolznz** [comment]
This was just merged and will be in the next release :rocket: https://github.com/getAlby/go/pull/158
