### ISSUE TITLE
Gracefully handle missing permissions / methods

### ISSUE THREAD

**Issue by rolznz** [getAlby/go#172]
Currently we do not allow a user to create a wallet if it has missing permissions.

e.g. if `list_transactions` is not supported, only show an error on the transactions list that "List Transactions is not supported by your wallet.".
e.g. if `pay_invoice` is not supported, only fail when attempting to make a payment. This allows for receive-only wallets.

**Comment by im-adithya** [comment]
But what should be the hard requirements? `get_balance` and one of `make_invoice` / `pay_invoice`?

And what is better:
- Greying out the Send button (or)
- Showing error toast when trying to attempt a payment (Showing `This app does not have the pay_invoice scope` error)

And similarly hardcoding a "This wallet doesn't support listing transactions" over showing error

I personally feel showing less errors is better, but that would mean writing if/else code for these cases

**Comment by rolznz** [comment]
I think just error toasts for a first iteration is ok! it is low effort and fixes the main issue.
