### ISSUE TITLE
Long description hides fee on transaction details page

### ISSUE THREAD

**Issue by rolznz** [getAlby/go#182]
From https://discord.com/channels/1257746232353230930/1280637076445859892/1301672147088834560

![image](https://github.com/user-attachments/assets/71018f35-1cb9-4daf-8300-d706d551c7b7)

**Comment by im-adithya** [comment]
The user can scroll down to see the fee, this page is scrollable. How to best show that? cc @stackingsaunter

**Comment by stackingsaunter** [comment]
Fees should be above Payment hash for sure.
