### ISSUE TITLE
[Improvement] Active wallet name

### ISSUE THREAD

**Issue by Darth-Coin** [getAlby/go#214]
I would like to propose an improvement in UI.
Display on top of the screen somewhere in a corner the name of the active wallet.
I use Alby Go with multiple accounts and sometimes I can't remember which one was last selected and I send sats.
![alby-go-multiple-accounts](https://github.com/user-attachments/assets/87b0702c-6249-4a7e-96aa-5a8cfdb2a8d8)

**Comment by stackingsaunter** [comment]
![image](https://github.com/user-attachments/assets/4cf3a47d-68f0-4c27-ab32-370264572500)

Let's do it this way, but let's only display it if there's more than 1 wallet connected

[Link to Figma ](https://www.figma.com/design/g8GdZzoYycE54ftt1ji5Lj/%F0%9F%91%A9%E2%80%8D%F0%9F%9A%80-Alby-Go?node-id=1362-24096&t=NMlrC3esskxibAzK-4)
