### ISSUE TITLE
iPad inconsistencies

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/go#22]
- [ ] iPad 13 (iPad 11 is fine)
![chrome_4hf6vQ3JH1](https://github.com/user-attachments/assets/ef3c7948-e2db-4e18-944f-743a6e47dd6b)

- [ ] iPad 14: first installation attempt was not successful. I need to check again.

**Comment by im-adithya** [comment]
How did you check this? BrowserStack?

This is from my 11-inch iPad Pro M1, 2021. Feels good overall except for the wayyy big send/receive buttons 😄 

<table>
<tr>
<td>
<img src="https://github.com/user-attachments/assets/d1e123ee-de2f-47ee-8fe4-616f4b24a4e4" />
</td>
<td>
<img src="https://github.com/user-attachments/assets/01c91af1-6cd0-474d-83d6-c8ac19c795ff" />
</td>
<td>
<img src="https://github.com/user-attachments/assets/8959e255-0b81-4f1e-828d-1cda06aaedd7" />
</td>
<td>
<img src="https://github.com/user-attachments/assets/53af117a-15d2-48ee-b4cb-fd05fc82d25f" />
</td>
</tr>

<tr>
<td>
<img src="https://github.com/user-attachments/assets/4f4eace5-e2a4-438b-a7b0-96e6ef051baf" />
</td>
<td>
<img src="https://github.com/user-attachments/assets/f5057541-2704-41fd-9c05-cf2ccd38dd1b" />
</td>
<td>
<img src="https://github.com/user-attachments/assets/137d9deb-d5e2-4859-9ebe-aa3b799a50f2" />
</td>
</tr>
</table>

**Comment by im-adithya** [comment]
Closing for now
