### ISSUE TITLE
Balance screen UI improvements

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/go#54]
- [ ] Chevron icon should be "Solid" (from Popicons) and Secondary gray (gray500)
- [x] Make balance visually more centered If possible (eg. in the middle between buttons and top nav)
- [x] US$ -> use "$" in front or USD at the end
- [x] Use semi-bold for "sats"
- [ ] For settings, use "Settings-minimal" Popicon (line) with Secondary gray (gray500)

![image](https://github.com/user-attachments/assets/1843ae48-b4f3-4a99-a411-d5c11b30df9b)

**Comment by reneaaron** [comment]
> Icons

Icons will be migrated to popicons in a separate step #29
