### ISSUE TITLE
Allow to delete not connected wallets

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/go#92]
If there's no working NWC link you cannot delete the wallet now (it moves to scanner)

**Comment by stackingsaunter** [comment]
Ah you actually can, but first you need to select it and then go to wallets and click settings

**Comment by bumi** [comment]
I failed doing this, too (and wanted to create the same issue)

can we support swipping to delete? like in messenger apps? (it at least is a pattern on iOS)

**Comment by stackingsaunter** [comment]
That would be awesome actually. @bumi I'll come up with design

**Comment by reneaaron** [comment]
I don't think there should be any distinction between wallets & connection strings in the app. I think from a user's perspective it's a lot easier to understand if this is one entity and you can just delete a wallet (but not disconnect it).

**Comment by bumi** [comment]
+1 I just wanted to delete a connection/wallet whatever it is called.

**Comment by rolznz** [comment]
I wonder it's a bit strange that a wallet can be created without a connection string. Maybe wallets should only be created when a valid connection string is given.

**Comment by bumi** [comment]
btw. I also think that the name should come second and should be prefilled with the lud16 from the connection string or the getinfo call
